[package]
name = "csaf-rs"
description = "A parser for the CSAF standard written in Rust"
license = "Apache-2.0"
repository = "https://github.com/csaf-rs/csaf"
keywords = ["csaf"]
readme = "../README.md"
version = "0.2.0"
edition = "2021"

[dependencies]
regress = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
regex = "1"
glob = "0.3.2"
purl = "0.1"

[build-dependencies]
schemars = "0.8"
serde_json = "1"
typify = "0.3"
syn = "2"
prettyplease = "0.2"
thiserror = "2"
